### ISSUE TITLE
Add reference to Ralph Parshall study on return flows

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-hydrology#26]
Joe Frank suggested adding a reference to the Ralph Parshall study in the [return flows](http://stories.openwaterfoundation.org/co/swsi-story-sp-hydrology/#returnflows) section since it summarizes the information well and provides historical context.  The information was used in the [HB 1278 Study](http://southplatte.colostate.edu/resources.shtml?expanddiv=none) but I don't see it specifically mentioned there.  Need to see if there is an online version published.  I emailed Joe Frank to see if there is a preferred online version available.

**Comment by kswaim** [comment]
Received email from Joe Frank with the Parshall study attached.  Copied the report into a "resources" folder that can be accessed in the repository.  Added text to the Return Flows page that references the study and other resources.
