### ISSUE TITLE
fileparser.js needs documentation

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-hydrology#3]
The js/fileparser.js file needs internal comments.  It is unclear if it is third party code or from OWF, maybe from Marcel?  For now I am going to automatically add a version to the filename so as to bust the cache.  Need Justin to figure out more about it.

**Comment by jurentie** [comment]
Doing a search on all the files FileParser is never used and commenting this file out creates no issues when loading the page. It is my understanding that it is not being used so I am removing it from the repository.
